const A=[['Air Conditioner','❄️',1.42,3.10,1],['Refrigerator','🧊',.18,1.21,1],['Ceiling Fan','🌀',.07,.84,1],['Lights','💡',.12,.62,1],['Desktop PC','🖥️',.21,.73,1],['Television','📺',0,.42,0],['Washing Machine','🧺',0,.21,0],['Microwave','🍽️',0,.07,0],['Water Heater','🚿',0,.06,0],['EV Charger','🚗',0,0,0]];
function page(id,btn){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.getElementById('title').textContent=id==='dashboard'?'Electricity Dashboard':id==='saving'?'Energy Saving Center':id[0].toUpperCase()+id.slice(1)+' Monitor';if(btn){document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}if(id==='analytics'&&!window.w){window.w=1;new Chart(document.getElementById('week'),{type:'bar',data:{labels:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],datasets:[{label:'This week',data:[6.8,7.4,6.2,8.1,7,6.3,7.26]},{label:'Last week',data:[7.1,7.8,6.7,8.6,7.5,6.8,7.8]}]},options:{responsive:true,maintainAspectRatio:false}})}}
function render(){document.getElementById('apps').innerHTML=A.map((a,i)=>`<div class="app"><span style="font-size:27px">${a[1]}</span><button class="switch" onclick="toggle(${i})">${a[4]?'ON':'OFF'}</button><h3>${a[0]}</h3><p>${a[4]?'Currently running':'Currently off'}</p><div class="power">${a[2].toFixed(2)} kW</div><p>${a[3].toFixed(2)} kWh today</p></div>`).join('');let on=A.filter(x=>x[4]).sort((a,b)=>b[2]-a[2]);document.getElementById('active').textContent=on.length;document.getElementById('power').textContent=on.reduce((s,x)=>s+x[2],0).toFixed(2)+' kW';document.getElementById('quick').innerHTML=on.slice(0,4).map(a=>`<div><span style="font-size:22px">${a[1]}</span><b>${a[0]}</b><small>● ${a[2].toFixed(2)} kW · Running</small></div>`).join('')}
function toggle(i){A[i][4]=A[i][4]?0:1;A[i][2]=A[i][4]?[1.42,.18,.07,.12,.21,0,0,0,0,0][i]:0;render()}
function add(){let n=prompt('Appliance name:');if(n){A.push([n,'🔌',.1,0,1]);render()}}
function calc(v){let b=1486,n=Math.round(b*(1-v/100));document.getElementById('pct').textContent=v+'%';document.getElementById('newbill').textContent='₹'+n.toLocaleString('en-IN');document.getElementById('save').textContent='Save ₹'+(b-n).toLocaleString('en-IN')+'/month'}
setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),1000);
render();calc(22);
new Chart(document.getElementById('dayChart'),{type:'line',data:{labels:['12 AM','2','4','6','8','10 AM','12 PM','2','4','6','8','10 PM'],datasets:[{label:'kWh',data:[.12,.09,.1,.22,.34,.42,.55,.48,.61,.72,.94,1.08],tension:.35,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,title:{display:true,text:'kWh'}},x:{grid:{display:false}}}}});
new Chart(document.getElementById('pie'),{type:'doughnut',data:{labels:['AC','Refrigerator','Fan','Lights','PC'],datasets:[{data:[3.1,1.21,.84,.62,.73]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}});
